# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import assignment_prototype_pb2 as assignment__prototype__pb2


class communicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makerequest = channel.unary_unary(
                '/assignment_prototype.communicator/makerequest',
                request_serializer=assignment__prototype__pb2.RequestCall.SerializeToString,
                response_deserializer=assignment__prototype__pb2.RequestResponse.FromString,
                )
        self.getLogs = channel.unary_unary(
                '/assignment_prototype.communicator/getLogs',
                request_serializer=assignment__prototype__pb2.RequestLog.SerializeToString,
                response_deserializer=assignment__prototype__pb2.logResponse.FromString,
                )


class communicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makerequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_communicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makerequest': grpc.unary_unary_rpc_method_handler(
                    servicer.makerequest,
                    request_deserializer=assignment__prototype__pb2.RequestCall.FromString,
                    response_serializer=assignment__prototype__pb2.RequestResponse.SerializeToString,
            ),
            'getLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.getLogs,
                    request_deserializer=assignment__prototype__pb2.RequestLog.FromString,
                    response_serializer=assignment__prototype__pb2.logResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assignment_prototype.communicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class communicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makerequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/assignment_prototype.communicator/makerequest',
            assignment__prototype__pb2.RequestCall.SerializeToString,
            assignment__prototype__pb2.RequestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/assignment_prototype.communicator/getLogs',
            assignment__prototype__pb2.RequestLog.SerializeToString,
            assignment__prototype__pb2.logResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
